### PR TITLE
Add rendering for CommercialTransaction

### PR DESCRIPTION
**Pull request by MiZiet**

### CODE REVIEW

**Review by getlarge — CHANGES_REQUESTED** [review]
I think you can change several things
- since there is not typing, plain JS should be fine
- Translations should be handled 
- the CommecialTransaction rendering should follow the structuring from the screenshot attached

Screenshot 2020-11-03 at 09 01 19

**Comment by MiZiet** [comment]
Thanks for a review, I'm currently working on translations.
I think the structure I got is similar to what you send, I have to add commercial transaction header.
[generating.pdf](https://github.com/s1seven/EN10168-schemas/files/5480009/generating.pdf)

**Review by getlarge — CHANGES_REQUESTED** [review]
Changes look good! Just few things to ask.

**Comment by getlarge** [comment]
Transfered to [schema-tools](https://github.com/s1seven/schema-tools)

**Pull request closed without merging**
